# enhanced_training.yaml - Configuration demonstrating model improvements
root_dir: null
valid_filepath: null
train_filepath: null
test_filepath: null
checkpoint_path: null
mode: train # train or eval

train:
  learning_rate: 0.0001
  num_epochs: 50
  batch_size: 8
  class_weights: [1, 1]
  auto_class_weights: true  # Automatically compute class weights from training data
  ignore_index: -100
  weight_decay: 0.01
  lr_scheduler: "reduce_on_plateau"  # Use ReduceLROnPlateau for better convergence
  early_stopping: true
  early_stopping_patience: 15

model:
  freeze_backbone: False
  num_classes: 2
  use_improved_model: true  # Use enhanced model with skip connections and attention
  use_attention: true  # Use attention mechanisms
  use_skip_connections: true  # Use skip connections

dataloader:
  bands: [1, 2, 3, 8, 11, 12] # Blue, Green, Red, Narrow NIR, SWIR 1, SWIR 2
  mean: [0.14245495, 0.13921481, 0.12434631, 0.31420089, 0.20743526, 0.12046503]
  std: [0.04036231, 0.04186983, 0.05267646, 0.0822221, 0.06834774, 0.05294205]
  img_size: 224
  temporal_dim: 1
  replace_label: [-1, 2]
  reduce_to_zero: False
  no_data_value: -9999
  constant_multiplier: 1.0
  # Enhanced data augmentation settings
  apply_color_jitter: true
  apply_rotation: true
  rotation_degrees: 15.0  # Increased rotation range
  # Multi-scale training settings
  multi_scale_training: true  # Enable multi-scale training
  multi_scale_sizes: [224, 256, 288, 320]

test:
  img_size: 224
  crop_size: 224
  stride: 224
  mask_cloud: False